appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32ce7c302eb707003c0975
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: ki4B/Syf4ky/sOcDL/hNlppyQEpVBU0DNhZy0ifEZLMmRNiHTUXvzEcb0RptAeDAiIybh8/qBmYkkClXytQmAEtPO/cKI6XGlRyGyXG31gMm9wa3muLKan5p1KZmlOFE+CzOlWB8EqRuOFdTlrLl7qDsVrLokfbXuzOG2Mg8WvLzEeZmOmIHB9i2FTkYBo3wX0iJWM8Tl+bsrRfyhc/YaFdsJACmA1/i9BNJP1JHSSCT823pJO5mOCeQ93svzC5nkofxAJmj4IqfsHHcrS+zVlFiz9zWdRXM/ovSi7E2F6oIy44yenjRG7ujLuInQrlel4R+H8dT63PEu1TgkGxjwwHtKQJaYv5tUD6kCHrWzDGTtBoS+ebjFDlliY7dgZP2sRCN/zU50krZ94ZdMx/+XnJzvJ5vElH/Sjqg/lkUk0mlN3NoH8+2mjGWLIqP/FY2F+SQFlXx4HVt9pHb0NxHrluGjYzB4P6b/ATgTwXaOzQ183A7yigCnfo6Ka3epJ9iwuQUYsvbIukL1LnN5GPdtqF/P5RUadINvmWV/0Ew84wE03jfzXyisYEWTQzD2cbquB/I5MfasHGqbaey+MLcCbRkz2L7Pi0tpdCARt+Y5yzqoZqjwkc9vgjv4si5pSHYq13apT/oRuM8TCN2XEzx/J7N7/EE76c+fSdkZ05NFFI=}
